"""Added is_banned column to user

Revision ID: 00d4ae939070
Revises: 2c138e3d91e2
Create Date: 2024-04-02 14:01:38.092694

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00d4ae939070"
down_revision: Union[str, None] = "2c138e3d91e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_banned", sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET is_banned = false")
    op.alter_column("users", "is_banned", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_banned")
    # ### end Alembic commands ###
